### ISSUE TITLE
Telegram Can't Send the Notification

### ISSUE THREAD

**Issue by muslimcodeid** [filipnet/checkmk-telegram-notify#12]
Hi,

I need your advice why i can't send the notif using this plugin.
I refer to these instructions https://github.com/filipnet/checkmk-telegram-notify and https://checkmk.com/blog/checkmk-notifications-via-telegram however when i try to send test notifiictation,its not send anything

https://pasteboard.co/VAPkehWiIjj5.png
https://pasteboard.co/p52fZV5dIPU4.png

omd version
OMD - Open Monitoring Distribution Version 2.1.0p18.cfe

Thanks in advance

**Comment by filipnet** [comment]
Hello, it is certainly not an issue with the script, but a configuration problem.
You should first try to initiate a "curl call" from the Linux command line. See for this: https://github.com/filipnet/checkmk-telegram-notify/issues/1#issuecomment-760677763
Only when this works, you could add lines of code at the beginning of the script for dry runs/debugging:
```
NOTIFY_PARAMETER_1="1234567890:AABBCCDDEEFFGG_HHIIJJKKLLMMNNOOPPQQRR"
NOTIFY_PARAMETER_2="-100200300400"
NOTIFY_PARAMETER_3=""
MESSAGE="Test"
```

**Comment by muslimcodeid** [comment]
Hi,

Thanks for your reply.

I did "curl call" and its working also i tried to add the lines you have mentioned above into the the script its working also but i got the following results

Invalid privacy parameter, check your Check_MK settings.
{"ok":true,"result":{"message_id":577,"sender_chat":{"id":#chatgroupid,"title":"#title","type":"channel"},"chat":{"id":-#id,"title":"#title","type":"channel"},"date":1673424955,"text":"()\n\ufe0f  \n\nState changed from  to \n\n\nIPv4:  \nIPv6: \n | mysite"}}OMD[mysite]:~/local/share/check_mk/notifications$ 

fyi,i am not enable PRIVACY ANONYMIZATION / MASQUERADING

Please Advice

Thanks in advance

**Comment by filipnet** [comment]
As you've probably already read, I write in the README: "_There are a lot of good instructions for this on the Internet, so this is not part of this documentation_". Maybe you have followed a "less good" guide? Look at: https://core.telegram.org/bots

I compared your output and mine:
https://github.com/filipnet/checkmk-telegram-notify/blob/main/docs/issues/12/comparison_output.png
And it seems that something is wrong with your bot and its posting into the channel (should be a supergroup). You should check and have a look for it.

**Comment by muslimcodeid** [comment]
I realized that i am using channel instead of telegram group but i created gruoup with supergroup however the issue is still happened,i have no idea about this

**Comment by filipnet** [comment]
Please detach yourself mentally from this script-solution in the first step, it works. Your challenge is to create a group, create a bot and send messages to the existing group.
