### ISSUE TITLE
Multiple notifications

### ISSUE THREAD

**Issue by lollilol** [filipnet/checkmk-telegram-notify#13]
Hi,

for the script to work, i need to put any user in the contact group "all".
It works fine if there is only 1 user in the contact group, however if i add more users into the contact group, the more i add, the more messages will be sent. For example 3 users = 3 messages (duplicates)

how is this supposed to be configured correctly?

greetings and thanks
Jascha

**Comment by filipnet** [comment]
Hi, Please have a look at this closed issue: https://github.com/filipnet/checkmk-telegram-notify/issues/1
