### ISSUE TITLE
Setting up Push Notfication

### ISSUE THREAD

**Issue by martinschaible** [filipnet/checkmk-telegram-notify#15]
Hi

I'm using Checkmk version 2.2.0. I copied the mail notification rule and i choosed "Push Notification (using Telegram)". I see only one field for entering the parameters of the bot. Your screenshot shows three input boxes.

Any idea what is going on?

Thanks!

Martin

**Comment by filipnet** [comment]
Hi Martin, please have a look at #6

**Comment by martinschaible** [comment]
Hi,

That's really odd, nice trap :-) But thanks for the advice. I will try it later on and will give feedback.

**Comment by martinschaible** [comment]
It worked out.
