### ISSUE TITLE
Store any errors somewhere

### ISSUE THREAD

**Issue by Commifreak** [filipnet/checkmk-telegram-notify#16]
I noticed spooler failed notifications because the script was unable to send any message.

I see that the script echoes some messages as well as the telegram reponse to stderr. Where is this then being recognized?

If no where, I would suggest that the script redirects any error to a log inside the site's tmp folder..?

**Comment by Elompenta** [comment]
@Commifreak You can get the error output from "/omd/sites/{sitename}/var/log/notify.log"

**Comment by filipnet** [comment]
This is also described in the "troubleshooting" chapter, so there is no problem in the code.
