### ISSUE TITLE
Update Script to Check_mk Version 2.0.0

### ISSUE THREAD

**Issue by tzockt** [filipnet/checkmk-telegram-notify#5]
Hi,
can you please update your script and instructions to Check_mk version 2.0.0.
Thanks!

**Comment by filipnet** [comment]
Hello, the script also works with Check_MK in version 2.0.0. The configuration is slightly different due to the new structure of the dashboard. I have now described this in the README.md and added screenshots. Please have a look if you can handle it.

**Comment by tzockt** [comment]
Hi,
it works fine but the Telegram Messages come twice.

**Comment by filipnet** [comment]
Since I cannot reproduce this on two Check_MK instances I assume a configuration fault.
Have you seen and checked this? Link: https://github.com/filipnet/checkmk-telegram-notify/issues/1

**Comment by tzockt** [comment]
Sorry my fault,. I send to all Users 😄

**Comment by filipnet** [comment]
Ok, great. The project is still very young, if you use it successfully and like it, I would be happy if you support the repository-rating with a star.

**Comment by tuannt76** [comment]
i am having a problem that i can only send to 1 telegram user.How can send notifications to multiple users telegram

**Comment by tuannt76** [comment]
i am having a problem that i can only send to 1 telegram user.How can send notifications to multiple users telegram
