### ISSUE TITLE
Issue with chmk 2.0.5 only on form field for parameters

### ISSUE THREAD

**Issue by mr2017x** [filipnet/checkmk-telegram-notify#6]
Hello and good morning,

after updating cmk only shows one instead of three form fields for parameter configuration. may you can have a look at, thanks in advance

**Comment by filipnet** [comment]
Hello, as far as I remember only one parameter field is displayed by default, further fields appear only if this was filled with a value. Is this excluded as a source of error? Unfortunately I cannot reproduce it the next days.

**Comment by filipnet** [comment]
In OMD - Open Monitoring Distribution **Version 2.0.0p5.cre** there is also **no limitation to only one parameter field**. This has been shown by a test in the sandbox. This is not a bug of Check_MK or checkmk-telegram-notify.
