### ISSUE TITLE
little warning on line 29, fixed

### ISSUE THREAD

**Issue by riccardospeggiorin-centropaghe** [filipnet/checkmk-telegram-notify#8]
I was taking a look at the notify log and notice this warning/error:

`check_mk_telegram-notify.sh: line 29: [: =: unary operator expected`

Line 29 is this:
`if [ ${NOTIFY_PARAMETER_3} = "privacy" ]; then`

I fix it with (like you did on line 63):
`if [[ ${NOTIFY_PARAMETER_3} == "privacy" ]]; then`

hope it helps.
bye

**Comment by filipnet** [comment]
Thank you for this information and especially directly the solution for this. I just modified the code and made a reference to the notify.log in the "troubleshooting" chapter.
