### ISSUE TITLE
Service notification delay not working 

### ISSUE THREAD

**Issue by Rdago** [filipnet/checkmk-telegram-notify#9]
Hi ! 

Script is working but it looks like delayed notification option is totally ignored and notifications are send immediately. Is there a way to make the delay work again? 

Thanks.

**Comment by filipnet** [comment]
Hello, I use "**Delay Host Notifications**" _(Setup > Hosts > Host Monitoring Rules > Delay Host Notifications)_ and "**Delay Service Notifications**" _(Setup > Services > Service Monitoring Rules > Delay Service Notifications)_ on a CheckMK instance myself, and it works. This is not an issue with the script, which is only triggered by Check_MK (delay occurs here).
